version: '3.8'

services:
  app:
    container_name: ebanx_app
    build: .
    volumes:
      - ./app:/app/app/
      - ./app/data:/app/data/
      - ./app/htmlcov/:/app/app/htmlcov/
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge