# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install -r app/requirements.txt
    - name: Test with coverage
      run: |
        make coverage-test
    - name: Generate coverage badge
      run: coverage-badge -o coverage.svg

    - name: Display coverage percentage
      run: |
      echo "Coverage Percentage: $(sed -n 's/.*<text x="23" y="18" class="coverage-percentage">\([^%]*\)%<\/text>.*/\1/p' coverage.svg)%"

    - name: Upload coverage badge as artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-badge
        path: coverage.svg